using UnityEngine;

namespace SuspiciousGames.Saligia.Core.Entities.Buffs
{
    public class ManaRegenBuff : Buff
    {
        private ManaRegenBuffData _data;
        private float _accumulatedRegeneration;
        private bool _isFullMana;

        private int _manaRegenerated;

        public ManaRegenBuff(BuffData buff, Entity buffTarget, Entity buffSource) : base(buff, buffTarget, buffSource)
        {
            _data = (ManaRegenBuffData)BuffData;
        }

        protected override void ApplyEffect()
        {
            _accumulatedRegeneration = 0.0f;
            _manaRegenerated = 0;
        }

        public override void Tick(float delta)
        {
            base.Tick(delta);

            _isFullMana = buffTarget.CastCostComponent.CurrentMindPower == buffTarget.CastCostComponent.MaxMindPower;

            if (_isFullMana)
            {
                buffTarget.BuffComponent.RemoveBuff(BuffData);
                return;
            }

            _accumulatedRegeneration += delta * _data.PercentualManaRegenerationValue / BuffData.Duration;

            if (_accumulatedRegeneration >= 1.0f)
            {
                buffTarget.CastCostComponent.AddMindPower(_accumulatedRegeneration, ignoreRegenMultipliers: true);
                _manaRegenerated = (int)_accumulatedRegeneration;
            }
            _accumulatedRegeneration -= (int)_accumulatedRegeneration;
        }

        protected override void UndoEffect()
        {
            Debug.Log("Mana regenerated by: " + _manaRegenerated);
        }
    }
}
